{% set name = "log2d" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/log2d-{{ version }}.tar.gz
  sha256: e5ed3e2b5632ab6eeb0ec5ebf6c134f53e47e7834331154a20d898752ea1dc94

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cleverdict
    - python >={{ python_min }}

test:
  imports:
    - log2d
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Pfython/log2d
  summary: Simple, sane, and sensible Logging
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
